version: '3.8'

services:
  telegram_bot:
    build: .
    container_name: telegram_viewer_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./sessions:/app/sessions
    command: python main.py
